"""Added test column in items

Revision ID: 2820965e0828
Revises: 
Create Date: 2022-01-10 00:40:33.522989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2820965e0828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('test1', sa.String(), nullable=True))
    op.drop_index('ix_items_test', table_name='items')
    op.create_index(op.f('ix_items_test1'), 'items', ['test1'], unique=False)
    op.drop_column('items', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_items_test1'), table_name='items')
    op.create_index('ix_items_test', 'items', ['test'], unique=False)
    op.drop_column('items', 'test1')
    # ### end Alembic commands ###
